// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzsaMcWmRn6tkwKYmRqBwp0FeJ7P5z7jw',
    appId: '1:175271811647:web:00cfd1e254aa4a6d47b68a',
    messagingSenderId: '175271811647',
    projectId: 'flutter-chat-by-sanskar',
    authDomain: 'flutter-chat-by-sanskar.firebaseapp.com',
    databaseURL: 'https://flutter-chat-by-sanskar-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-chat-by-sanskar.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOeUWVYXi1csfbXyX2Sisb8PDGP08c0Dw',
    appId: '1:175271811647:android:544f57f6736824ea47b68a',
    messagingSenderId: '175271811647',
    projectId: 'flutter-chat-by-sanskar',
    databaseURL: 'https://flutter-chat-by-sanskar-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-chat-by-sanskar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaOS0fmhYDP-sD9jiDfo3t3O09QwO-ETE',
    appId: '1:175271811647:ios:750616936cb4154a47b68a',
    messagingSenderId: '175271811647',
    projectId: 'flutter-chat-by-sanskar',
    databaseURL: 'https://flutter-chat-by-sanskar-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-chat-by-sanskar.appspot.com',
    iosBundleId: 'com.skv.bateinKaro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaOS0fmhYDP-sD9jiDfo3t3O09QwO-ETE',
    appId: '1:175271811647:ios:d0a9f3f01a5af45847b68a',
    messagingSenderId: '175271811647',
    projectId: 'flutter-chat-by-sanskar',
    databaseURL: 'https://flutter-chat-by-sanskar-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-chat-by-sanskar.appspot.com',
    iosBundleId: 'com.skv.bateinKaro.RunnerTests',
  );
}
